#!/bin/bash

#PBS -N analysis

#PBS -A wellman_flux
#PBS -q flux
#PBS -l qos=flux
#PBS -W group_list=wellman

#PBS -l walltime=06:00:00
#PBS -l nodes=1:ppn=1,pmem=4000mb

#PBS -M liuyaoly@umich.edu
#PBS -m abe
#PBS -V
#PBS -W umask=0007

umask 0007

module load python/2.7.5

mkdir /tmp/${PBS_JOBID}
cp -r /Users/yaoliu/Desktop/egtaonline3/public/egtaonline/analysis/21/in/21-analysis-20140208114933EDT.json /tmp/${PBS_JOBID}
      
cp -r /Users/yaoliu/Desktop/egtaonline3/public/GameAnalysis/scripts/Reductions.py /tmp/${PBS_JOBID}
cp -r /Users/yaoliu/Desktop/egtaonline3/public/GameAnalysis/AnalysisScript.py /tmp/${PBS_JOBID}
cd /tmp/${PBS_JOBID}

export PYTHONPATH=$PYTHONPATH:/Users/yaoliu/Desktop/egtaonline3/public/GameAnalysis    
      
python Reductions.py -input 21-analysis-20140208114933EDT.json -output 21-reduced-20140208114933EDT.json DPR 5 
python AnalysisScript.py -r  -d  -s  -c  -i  21-reduced-20140208114933EDT.json > 21-analysis-20140208114933EDT.out


cp -r /tmp/${PBS_JOBID}/21-analysis-20140208114933EDT.out /Users/yaoliu/Desktop/egtaonline3/public/egtaonline/analysis/21/out
rm -rf /tmp/${PBS_JOBID}
