#!/bin/bash
#PBS -N analysis

#PBS -A wellman_flux
#PBS -q flux
#PBS -l qos=flux
#PBS -W group_list=wellman

#PBS -l walltime=06:00:00
#PBS -l nodes=1:ppn=1,pmem=4000mb

#PBS -M liuyaoly@umich.edu
#PBS -m abe
#PBS -V
#PBS -W umask=0007

umask 0007

module load python/2.7.5

mkdir /tmp/${PBS_JOBID}
cp -r /nfs/wellman_ls/egtaonline/analysis/21/in/21-analysis-20140408173204EDT.json /tmp/${PBS_JOBID}
      
cp -r /nfs/wellman_ls/GameAnalysis/Reductions.py /tmp/${PBS_JOBID}
cp -r /nfs/wellman_ls/GameAnalysis/scripts/AnalysisScript.py /tmp/${PBS_JOBID}
cd /tmp/${PBS_JOBID}

export PYTHONPATH=$PYTHONPATH:/nfs/wellman_ls/GameAnalysis    
      
python Reductions.py -input 21-analysis-20140408173204EDT.json -output 21-reduced-20140408173204EDT.json DPR 5 
python AnalysisScript.py -r 0.001 -d 0.001 -s 0.001 -c 1.0e-08 -i 10000 21-reduced-20140408173204EDT.json > 21-analysis-20140408173204EDT.out


cp -r /tmp/${PBS_JOBID}/21-analysis-20140408173204EDT.out /nfs/wellman_ls/egtaonline/analysis/21/out
rm -rf /tmp/${PBS_JOBID}
