#!/bin/bash
#PBS -N analysis

#PBS -A wellman_flux
#PBS -q flux
#PBS -l qos=flux
#PBS -W group_list=wellman

#PBS -l walltime=06:00:00
#PBS -l nodes=1:ppn=1,pmem=4000mb

#PBS -e /nfs/wellman_ls/egtaonline/analysis/23/pbs/23-analysis-20140808235209EDT-pbs.e
#PBS -o /nfs/wellman_ls/egtaonline/analysis/23/pbs/23-analysis-20140808235209EDT-pbs.o

#PBS -M liuyaoly@umich.edu
#PBS -m abe
#PBS -V
#PBS -W umask=0022

umask 0022

module load python/2.7.5
mkdir /tmp/${PBS_JOBID}
cp -r /nfs/wellman_ls/GameAnalysis/AnalysisScript.py /tmp/${PBS_JOBID}
cp -r /nfs/wellman_ls/egtaonline/analysis/23/in/23-analysis-20140808235209EDT.json /tmp/${PBS_JOBID}

cp -r /nfs/wellman_ls/GameAnalysis/Reductions.py /tmp/${PBS_JOBID}
cp -r /nfs/wellman_ls/GameAnalysis/Subgames.py /tmp/${PBS_JOBID}
cd /tmp/${PBS_JOBID}
export PYTHONPATH=$PYTHONPATH:/nfs/wellman_ls/GameAnalysis

      
python Reductions.py -input 23-analysis-20140808235209EDT.json -output 23-reduced-20140808235209EDT.json DPR 5
python Subgames.py detect  < 23-reduced-20140808235209EDT.json > 23-subgame.json
python AnalysisScript.py -r 0.001 -d 0.001 -s 0.001 -c 1.0e-08  -i 10000 -sg 23-subgame.json 23-reduced-20140808235209EDT.json > 23-analysis-20140808235209EDT.out


cp -r /tmp/${PBS_JOBID}/23-analysis-20140808235209EDT.out /nfs/wellman_ls/egtaonline/analysis/23/out
cp -r /tmp/${PBS_JOBID}/23-subgame.json /nfs/wellman_ls/egtaonline/analysis/23/subgame
rm -rf /tmp/${PBS_JOBID}

   
