#!/bin/bash
#PBS -N analysis

#PBS -A wellman_flux
#PBS -q flux
#PBS -l qos=flux
#PBS -W group_list=wellman

#PBS -l walltime=06:00:00
#PBS -l nodes=1:ppn=1,pmem=4000mb

#PBS -e /nfs/wellman_ls/egtaonline/analysis/14/4/14-analysis-4-pbs.e
#PBS -o /nfs/wellman_ls/egtaonline/analysis/14/4/14-analysis-4-pbs.o

#PBS -M liuyaoly@umich.edu
#PBS -m abe
#PBS -V
#PBS -W umask=0022

umask 0022

module load python/2.7.5
mkdir /tmp/${PBS_JOBID} 
cp -r /nfs/wellman_ls/GameAnalysis/AnalysisScript.py /tmp/${PBS_JOBID}
cp -r /nfs/wellman_ls/GameAnalysis/Reductions.py /tmp/${PBS_JOBID}
cp -r /nfs/wellman_ls/GameAnalysis/Subgames.py /tmp/${PBS_JOBID}
cp -r /nfs/wellman_ls/GameAnalysis/Dominance.py /tmp/${PBS_JOBID}
cd /tmp/${PBS_JOBID}
cp /nfs/wellman_ls/egtaonline/analysis/14/4/* .
mkdir out
export PYTHONPATH=$PYTHONPATH:/nfs/wellman_ls/GameAnalysis

python Reductions.py -input 14-analysis-4.json -output ./out/14-reduced-4.json DPR 2
python Dominance.py < ./out/14-reduced-4.json > ./out/14-dominance-4.json
python Subgames.py detect < ./out/14-dominance-4.json > ./out/./out14-subgame-4.json
python AnalysisScript.py -r 0.001 -d 0.001 -s  -c 0.00000001 -i 10000 -p 0  -sg ./out14-subgame-4.json    --verbose    -nd 14-dominance-4.json   ./out/14-reduced-4.json > ./out/14-analysis-4.txt

cp /tmp/${PBS_JOBID}/out/* /nfs/wellman_ls/egtaonline/analysis/14/4
rm -rf /tmp/${PBS_JOBID}

